pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git 'https://github.com/viraj-wagh/CI-CD-pipeline-project1.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("node-app")
                }
            }
        }
        stage('Deploy Container') {
            steps {
                script {
                    sh "docker rm -f node-app || true"
                    sh "docker run -d -p 3000:3000 --name node-app node-app"
                }
            }
        }
    }
}